### ISSUE TITLE
PermissionError on local_clifford_simulator and local_qiskit_simulator

### ISSUE THREAD

**Issue by psyhtest** [ctuning/ck-qiskit#2]
# Summary
`program:qiskit-demo` works fine on `local_unitary_simulator` and `local_qasm_simulator` but fails on `local_clifford_simulator` and `local_qiskit_simulator`.

# Install QISKit via CK
```
$ sudo apt install build-essential libblas-dev liblapack-dev python3 python3-pip
$ sudo pip3 install ck
$ ck pull repo:ck-qiskit
$ ck install package:lib-qiskit
```

# How to Reproduce

## [WORKS] `local_unitary_simulator`
```
$ ck run program:qiskit-demo --cmd_key=hello --env.CK_IBM_BACKEND=local_unitary_simulator
...
 (printing output files) 

    * tmp-stdout.tmp

      -- Ignoring SSL errors.  This is not recommended --
      WARNING: There's no connection with IBMQuantumExperience servers.
                   cannot test I/O intesive tasks, will only test CPU intensive tasks
                   running the jobs in the local simulator
      The backends available for use are:
      ['local_clifford_simulator',
       'local_qasm_simulator',
       'local_unitary_simulator',
       'local_qiskit_simulator']
      
      
      COMPLETED
      {'unitary': array([[ 0.70710678+0.00000000e+00j,  0.70710678-8.65956056e-17j,
               0.        +0.00000000e+00j,  0.        +0.00000000e+00j],
             [ 0.        +0.00000000e+00j,  0.        +0.00000000e+00j,
               0.70710678+0.00000000e+00j, -0.70710678+8.65956056e-17j],
             [ 0.        +0.00000000e+00j,  0.        +0.00000000e+00j,
               0.70710678+0.00000000e+00j,  0.70710678-8.65956056e-17j],
             [ 0.70710678+0.00000000e+00j, -0.70710678+8.65956056e-17j,
               0.        +0.00000000e+00j,  0.        +0.00000000e+00j]])}
      

    * tmp-stderr.tmp

```

## [WORKS] `local_qasm_simulator`
```
$ ck run program:qiskit-demo --cmd_key=hello --env.CK_IBM_BACKEND=local_qasm_simulator
...
 (printing output files) 

    * tmp-stdout.tmp

      -- Ignoring SSL errors.  This is not recommended --
      WARNING: There's no connection with IBMQuantumExperience servers.
                   cannot test I/O intesive tasks, will only test CPU intensive tasks
                   running the jobs in the local simulator
      The backends available for use are:
      ['local_clifford_simulator',
       'local_qiskit_simulator',
       'local_unitary_simulator',
       'local_qasm_simulator']
      
      
      COMPLETED
      {'counts': {'00': 512, '11': 512}}
      

    * tmp-stderr.tmp
```

## [FAILS] `local_clifford_simulator`

```
$ ck run program:qiskit-demo --cmd_key=hello --env.CK_IBM_BACKEND=local_clifford_simulator
...
 (printing output files) 

    * tmp-stdout.tmp

      -- Ignoring SSL errors.  This is not recommended --
      WARNING: There's no connection with IBMQuantumExperience servers.
                   cannot test I/O intesive tasks, will only test CPU intensive tasks
                   running the jobs in the local simulator
      The backends available for use are:
      ['local_clifford_simulator',
       'local_qiskit_simulator',
       'local_unitary_simulator',
       'local_qasm_simulator']
      
      
      ERROR
      

    * tmp-stderr.tmp

      concurrent.futures.process._RemoteTraceback: 
      """
      Traceback (most recent call last):
        File "/usr/lib/python3.5/concurrent/futures/process.py", line 175, in _process_worker
          r = call_item.fn(*call_item.args, **call_item.kwargs)
        File "/home/anton/CK_TOOLS/lib-qiskit-gcc-7.2.0-linux-64/build/qiskit/_jobprocessor.py", line 54, in run_backend
          return backend.run(q_job)
        File "/home/anton/CK_TOOLS/lib-qiskit-gcc-7.2.0-linux-64/build/qiskit/backends/_qiskit_cpp_simulator.py", line 132, in run
          result = run(qobj, self._configuration['exe'])
        File "/home/anton/CK_TOOLS/lib-qiskit-gcc-7.2.0-linux-64/build/qiskit/backends/_qiskit_cpp_simulator.py", line 158, in run
          stdin=PIPE, stdout=PIPE, stderr=PIPE) as proc:
        File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
          restore_signals, start_new_session)
        File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
          raise child_exception_type(errno_num, err_msg)
      PermissionError: [Errno 13] Permission denied
      """
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "../hello_quantum.py", line 55, in <module>
          print(result.get_data("bell"))
        File "/home/anton/CK_TOOLS/lib-qiskit-gcc-7.2.0-linux-64/build/qiskit/_result.py", line 204, in get_data
          raise exception
        File "/home/anton/CK_TOOLS/lib-qiskit-gcc-7.2.0-linux-64/build/qiskit/_jobprocessor.py", line 99, in _job_done_callback
          result = future.result()
        File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
          return self.__get_result()
        File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
          raise self._exception
      PermissionError: [Errno 13] Permission denied
```

## [FAILS] `local_qiskit_simulator`
```
$ ck run program:qiskit-demo --cmd_key=hello --env.CK_IBM_BACKEND=local_qiskit_simulator
...
 (printing output files) 

    * tmp-stdout.tmp

      -- Ignoring SSL errors.  This is not recommended --
      WARNING: There's no connection with IBMQuantumExperience servers.
                   cannot test I/O intesive tasks, will only test CPU intensive tasks
                   running the jobs in the local simulator
      The backends available for use are:
      ['local_unitary_simulator',
       'local_qiskit_simulator',
       'local_clifford_simulator',
       'local_qasm_simulator']
      
      
      ERROR
      

    * tmp-stderr.tmp

      concurrent.futures.process._RemoteTraceback: 
      """
      Traceback (most recent call last):
        File "/usr/lib/python3.5/concurrent/futures/process.py", line 175, in _process_worker
          r = call_item.fn(*call_item.args, **call_item.kwargs)
        File "/home/anton/CK_TOOLS/lib-qiskit-gcc-7.2.0-linux-64/build/qiskit/_jobprocessor.py", line 54, in run_backend
          return backend.run(q_job)
        File "/home/anton/CK_TOOLS/lib-qiskit-gcc-7.2.0-linux-64/build/qiskit/backends/_qiskit_cpp_simulator.py", line 87, in run
          result = run(qobj, self._configuration['exe'])
        File "/home/anton/CK_TOOLS/lib-qiskit-gcc-7.2.0-linux-64/build/qiskit/backends/_qiskit_cpp_simulator.py", line 158, in run
          stdin=PIPE, stdout=PIPE, stderr=PIPE) as proc:
        File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
          restore_signals, start_new_session)
        File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
          raise child_exception_type(errno_num, err_msg)
      PermissionError: [Errno 13] Permission denied
      """
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "../hello_quantum.py", line 55, in <module>
          print(result.get_data("bell"))
        File "/home/anton/CK_TOOLS/lib-qiskit-gcc-7.2.0-linux-64/build/qiskit/_result.py", line 204, in get_data
          raise exception
        File "/home/anton/CK_TOOLS/lib-qiskit-gcc-7.2.0-linux-64/build/qiskit/_jobprocessor.py", line 99, in _job_done_callback
          result = future.result()
        File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
          return self.__get_result()
        File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
          raise self._exception
      PermissionError: [Errno 13] Permission denied
```

**Comment by psyhtest** [comment]
For the record, I've reproduced this issue on the TX1.

**Comment by psyhtest** [comment]
As @diego-plan9 suggested in https://github.com/QISKit/qiskit-sdk-py/issues/344, I printed the value of `executable` passed to the `run(qobj, executable)` method. It turned out it was not a file but a directory that contained the `qiskit_simulator` executable:
```
$ ls -la /home/anton/CK_TOOLS/lib-qiskit-gcc-6.3.0-linux-64/build/out/
total 1316
drwxr-xr-x  2 anton dvdt   4096 Mar 15 10:51 .
drwxr-xr-x 55 anton dvdt   4096 Mar 15 10:51 ..
-rw-r--r--  1 anton dvdt 857800 Mar 15 10:51 main.o
-rwxr-xr-x  1 anton dvdt 477224 Mar 15 10:51 qiskit_simulator
```

This is probably coming from the patch that we apply:
```
diff --git a/qiskit/backends/_qiskit_cpp_simulator.py b/qiskit/backends/_qiskit_cpp_simulator.py
index 4bcf8d1..dadfadd 100644
--- a/qiskit/backends/_qiskit_cpp_simulator.py
+++ b/qiskit/backends/_qiskit_cpp_simulator.py
@@ -43,6 +43,9 @@ DEFAULT_SIMULATOR_PATHS = [
                     '../../../out/src/qiskit-simulator/qiskit_simulator' + EXTENSION),
     # This is the path where PIP installs the simulator
     os.path.abspath(os.path.dirname(__file__) + '/qiskit_simulator' + EXTENSION),
+    # This is the path where CK installs the simulator
+    os.environ['CK_ENV_LIB_QISKIT_SIM']
+
 ]

```
It seems we should either join the `CK_ENV_LIB_QISKIT_SIM` path with the executable name here, or preferably fix it in the env which currently says:
```
export CK_ENV_LIB_QISKIT_SIM=/home/anton/CK_TOOLS/lib-qiskit-gcc-6.3.0-linux-64/build/out/
```

I'll check this later.

**Comment by psyhtest** [comment]
I've fixed the env, and can run the demo on the simulator!

**Comment by fvella** [comment]
That's great!!! I will test on velociti in case I will close the issue
